#!/usr/bin/env python
################################################################
####
#### This file is part of the `pylauncher' package
#### for parametric job launching
####
#### Copyright Victor Eijkhout 2010-2024
#### eijkhout@tacc.utexas.edu
####
#### https://github.com/TACC/pylauncher
####
#### make_commandlines.py : generate a file of launcher commandlines
####
################################################################

import sys

if len(sys.argv)!=5:
    print("Usage: make_commandlines.py command njobs tmin tmax")
    print(f"Not: {sys.argv}")
    sys.exit(1)

prog,command,njobs,tmin,tmax = sys.argv

cfile = open("commandlines","w")
cfile.write("####\n");
cfile.write("#### This file was automatically generated by: \n");
cfile.write("#### python %s \n" % (sys.argv));
cfile.write("####\n");

for i in range(int(njobs)):
    j = "%s %s %s" % (command,tmin,tmax)
    cfile.write( str(j) + "\n" )
    
cfile.close()

print("Written file `commandlines'")
