#!/usr/bin/env python3
################################################################
####
#### This utility is part of the pylauncher distribution
#### Victor Eijkhout eijkhout@tacc.utexas.edu copyright 2010-2020
####
#### make_commandlines.py : generate a file of launcher commandlines
####
################################################################

import sys
import pylauncher3

if len(sys.argv)!=4:
    print("Usage: make_commandlines.py njobs tmin tmax")
    sys.exit(1)

prog,njobs,tmin,tmax = sys.argv
tmin = int(tmin)
tmax = int(tmax)

outputfilename = "sleepcommandlines"
cfile = open(outputfilename,"w")
cfile.write("####\n");
cfile.write("#### This file was automatically generated by: \n");
cfile.write("#### python %s \n" % (sys.argv));
cfile.write("####\n");
g = pylauncher3.SleepCommandGenerator(tmin=tmin,tmax=tmax)
for i in range(int(njobs)):
    command = g.next()
    j = "%s" % (command)
    cfile.write( str(j) + "\n" )
    
cfile.close()

print("Written file `%s'" % outputfilename)
