#!/usr/bin/env python
################################################################
####
#### This utility is part of the pylauncher distribution
#### Victor Eijkhout eijkhout@tacc.utexas.edu copyright 2010-2020
####
#### make_commandlines.py : generate a file of launcher commandlines
####
################################################################

import sys
import pylauncher3

if len(sys.argv)!=5:
    print("Usage: make_commandlines.py command njobs tmin tmax")
    sys.exit(1)

prog,command,njobs,tmin,tmax = sys.argv

cfile = open("commandlines","w")
cfile.write("####\n");
cfile.write("#### This file was automatically generated by: \n");
cfile.write("#### python %s %s %s %s %s\n" % (prog,command,njobs,tmin,tmax));
cfile.write("####\n");
for i,c in zip( range(int(njobs)),\
                pylauncher3.CountedCommandGenerator(command=command,\
                                                    tmin=int(tmin),tmax=int(tmax))):
    cfile.write( c+"\n" )
cfile.close()

print("Written file `commandlines'")
