#!/usr/bin/env python
################################################################
####
#### This utility is part of the pylauncher distribution
#### Victor Eijkhout eijkhout@tacc.utexas.edu copyright 2010-2020
####
#### make_commandlines.py : generate a file of launcher commandlines
####
################################################################

import sys
import pylauncher3

if len(sys.argv)!=5:
    print("Usage: make_commandlines.py command njobs tmin tmax")
    sys.exit(1)

prog,command,njobs,tmin,tmax = sys.argv

cfile = open("commandlines","w")
cfile.write("####\n");
cfile.write("#### This file was automatically generated by: \n");
cfile.write("#### python %s \n" % (sys.argv));
cfile.write("####\n");
##g = pylauncher3.CountedCommandGenerator(command=command)
for i in range(int(njobs)):
    j = "%s %s %s" % (command,tmin,tmax)
    cfile.write( str(j) + "\n" )
    
cfile.close()

print("Written file `commandlines'")
